# -*- coding: utf-8 -*-
"""Valerie_Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Yja0i261NvG04O6L2rvl456GpDBLGia

# Data extraction
"""

import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

st.title("Cars dataset exploration")
url = "https://raw.githubusercontent.com/murpi/wilddata/master/quests/cars.csv"
df = pd.read_csv(url)
st.write("Dataset preview", df.head())
st.dataframe(df)

"""# Exploration"""
st.write("Dataset info", df.info())
print("---"*40)
st.write("Dataset description", df.describe(include="all"))
st.table(df.describe(include="all"))
print("---"*40)
st.write("Missed values", df.isna().sum())
print("---"*40)
st.write("There are : ", df.duplicated().sum(), " duplicates")
print("---"*40)

"""## Graphiques

"""

plt.title('Distribution of cars by continent')
car_countplot = sns.countplot(x='continent', data=df, palette='plasma')
st.pyplot(car_countplot)

plt.title('Distribution of cylinders by weight')
car_violinplot1 = sns.violinplot(x='cylinders', y='weightlbs', data=df, palette='plasma')
st.pyplot(car_violinplot1)

plt.title('Distribution of cylinders by cubicinches')
car_violinplot2 = sns.violinplot(x='cylinders', y='cubicinches', data=df, palette='plasma')
st.pyplot(car_violinplot2)

plt.title('Heatmap of correlation')
car_heatmap = sns.heatmap(df.select_dtypes("number").corr(), annot=True, center=0, cmap='plasma')
st.pyplot(car_heatmap)

plt.title('Pairplot of numerical columns')
car_pairplot = sns.pairplot(df.select_dtypes("number"), palette='plasma')
st.pyplot(car_pairplot)
